services:
  # Go Backend
  - type: web
    name: mini-meeting-backend
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /api/v1/health
    envVars:
      - key: PORT
        value: 3000
      - key: ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 24h
      - key: DATABASE_URL
        fromDatabase:
          name: mini-meeting-db
          property: connectionString
      - key: REDIS_HOST
        fromRedis:
          name: mini-meeting-redis
          property: host
      - key: REDIS_PORT
        fromRedis:
          name: mini-meeting-redis
          property: port
      - key: REDIS_USERNAME
        fromRedis:
          name: mini-meeting-redis
          property: username
      - key: REDIS_PASSWORD
        fromRedis:
          name: mini-meeting-redis
          property: password
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: LIVEKIT_URL
        sync: false
      - key: OPEN_ROUTER_API_KEY
        sync: false
      - key: OPEN_ROUTER_BASE_URL
        value: https://openrouter.ai/api/v1
      - key: OPEN_ROUTER_MODEL
        value: nvidia/nemotron-3-nano-30b-a3b:free
      - key: OPEN_ROUTER_TIMEOUT
        value: 300s
      - key: OPEN_ROUTER_MAX_TOKENS
        value: 4096
      - key: BRAVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        value: Mini Meeting
      - key: SUMMARIZER_CHUNK_DURATION_SECONDS
        value: "20"
      - key: SUMMARIZER_TEMP_DIR
        value: /tmp/summarizer

databases:
  - name: mini-meeting-db
    plan: free
    region: oregon
    ipAllowList: []

redis:
  - name: mini-meeting-redis
    plan: free
    region: oregon
