FROM golang:1.24.4-alpine

RUN apk add --no-cache git curl

# Install air for hot reloading
RUN go install github.com/air-verse/air@v1.52.3

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 3000

CMD ["air", "-c", ".air.linux.toml"]
